# Site settings
email: adalidnegro@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Said's blog
description: Blog personal de Said Fayad
url: ""
twitter_username: Adalid_Negro 
default_img: https://avatars0.githubusercontent.com/u/2597420?v=3&s=400

# Profile settings
name: Said Fayad
profile_img: https://avatars0.githubusercontent.com/u/2597420?v=3&s=400
profile: 
social:
  email: adalidnegro@gmail.com
  facebook: saeed-fayyad
  flickr: 
  github: AdalidNegro
  instagram:
  linkedin: adalidnegro
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: Adalid_Negro
  stackoverflow: users/3977303/adalid-negro # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCR7WcVqtWRyxCt6CHSyV7xA # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

theme: jekyll-theme-hacker
